/* eslint-disable import/prefer-default-export */
export const AUTHCONSTANTS = {
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN: 'LOGIN',
  LOGIN_ERROR: 'LOGIN_ERROR',
  LOGOUT: 'LOGOUT'
};

export const USERCONSTANTS = {
  SET_DASHBOARD: 'GET_DASHBOARD',
  SET_CALLOUT: 'SET_CALLOUT',
  SET_MAPDATA: 'SET_MAPDATA',
  SET_MONTH: 'SET_MONTH',
  SET_YEAR: 'SET_YEAR',
  SET_LOADING: 'SET_LOADING',
  SET_PERCENT: 'SET_PERCENT',
  SET_REPORT: 'SET_REPORT',
  SET_PARAMS: 'SET_PARAMS',
  SET_WORKTIME: 'SET_WORKTIME',
  SET_WORKGROUP: 'SET_WORKGROUP',
  SET_LOCATION: 'SET_LOCATION',
  SET_EMPLOYEES: 'SET_EMPLOYEES',
  SET_STUDENTS: 'SET_STUDENTS',
  SET_GUARDIANS: 'SET_GUARDIANS',
  SET_WARDS: 'SET_WARDS',
  SET_OOF: 'SET_OOF',
  SET_ABSENTEES: 'SET_ABSENTEES',
  SET_ALERT: 'SET_ALERT',
  SET_SUB: 'SET_SUB',
  SET_EMPLOYEE_TYPE: 'SET_EMPLOYEE_TYPE',
  COMP_LOAD: 'COMP_LOAD',
  SET_TERMINALS: 'SET_TERMINALS',
  SET_ALL_EMPLOYEES: 'SET_ALL_EMPLOYEES',
  UPDATE_BREADCRUMB: 'UPDATE_BREADCRUMB',
};
